import { useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import {
  Row, Col, Card, Form, Button,
} from 'react-bootstrap'; // react-bootstrap
import { ChevronRight, PersonFill } from 'react-bootstrap-icons';
import MilestoneRow from '../component/MilestoneRow'; // reusable component
import '../styles/theme.css';

// ─── Mock data (replace with API calls) ──────────────────────────────────────

const MOCK_KPI = {
  title: 'Monthly sales revenue target',
  description:
    'Total revenue generated by the assigned staff member within the calendar month, measured against the monthly sales quota set by the department head.',
  category: 'Project',
  department: 'Business Development',
  targetValue: '',
  unit: '',
  direction: 'Amount',
  startDate: '2025-01-01',
  deadline: '2025-04-30',
  milestones: [
    { id: 1, date: '2025-04-23', label: 'First week check-in' },
    { id: 2, date: '2025-04-27', label: 'Render' },
  ],
  evidencePdf: false,
  evidenceImages: true,
  evidenceSpreadsheet: true,
  staffInstructions: '',
};

const EMPTY_KPI = {
  title: '',
  description: '',
  category: '',
  department: '',
  targetValue: '',
  unit: '',
  direction: 'Amount',
  startDate: '',
  deadline: '',
  milestones: [],
  evidencePdf: false,
  evidenceImages: false,
  evidenceSpreadsheet: false,
  staffInstructions: '',
};

const ASSIGNED_STAFF = [
  { initials: 'AS', name: 'AakarSerman', bg: '#F9E7DE', color: '#C85A3A' },
  { initials: 'SR', name: 'SR Chen',     bg: '#E8F0ED', color: '#0B5E3A' },
];

// ─── Component ───────────────────────────────────────────────────────────────

const CreateEditKpi = () => {
  const navigate  = useNavigate();
  const { kpiId } = useParams();
  const isEdit    = Boolean(kpiId && kpiId !== 'new');

  const [form, setForm] = useState(isEdit ? MOCK_KPI : EMPTY_KPI);

  const set = (field, value) =>
    setForm((prev) => ({ ...prev, [field]: value }));

  const addMilestone = () =>
    setForm((prev) => ({
      ...prev,
      milestones: [...prev.milestones, { id: Date.now(), date: '', label: '' }],
    }));

  const updateMilestone = (id, updated) =>
    setForm((prev) => ({
      ...prev,
      milestones: prev.milestones.map((m) => (m.id === id ? { ...updated, id } : m)),
    }));

  const removeMilestone = (id) =>
    setForm((prev) => ({
      ...prev,
      milestones: prev.milestones.filter((m) => m.id !== id),
    }));

  return (
    <div
      style={{
        backgroundColor: 'var(--main-bg)',
        minHeight: '100vh',
        padding: '32px 48px',
        display: 'flex',
        justifyContent: '',
        alignItems: 'flex-start',
      }}
    >
      {/* Centred wrapper */}
      <div style={{ maxWidth: '960px', margin: '0 auto' }}>
        <h4 className="serif-font mb-3">
          {isEdit ? 'Edit KPI' : 'New KPI'}
        </h4>

        {/* Outer card — Card (react-bootstrap) */}
        <Card
          className="custom-card w-100"
        >
        
        {/* Card.Body — react-bootstrap */}
        <Card.Body className="p-0">
          

          {/* ── Header ─────────────────────────────────────────────── */}
          <div
            className="d-flex align-items-center justify-content-between px-5 py-4"
            style={{ borderBottom: '1px solid #F0EAE0' }}
          >
            

            <div className="d-flex align-items-center gap-2">
              {/* Button (outline) — react-bootstrap */}
              <Button
                size="sm"
                className="btn-light"
                onClick={() => navigate('/manager/all-kpis')}
              >
                Save as draft
              </Button>
              {/* Button (primary) — react-bootstrap */}
              <Button size="sm" className="btn-orange">
                Publish KPI
              </Button>
              {/* Button (close/link) — react-bootstrap */}
              <Button
                variant="link"
                className="p-1 text-muted text-decoration-none"
                style={{ fontSize: '18px', lineHeight: 1 }}
                onClick={() => navigate('/manager/all-kpis')}
              >
                ✕
              </Button>
            </div>
          </div>

          {/* ── Body: two-column layout ────────────────────────────── */}
          {/* Row — react-bootstrap */}
          <Row className="g-0">

            {/* ── LEFT: Form ─────────────────────────────────────── */}
            {/* Col — react-bootstrap */}
            <Col
              md={7}
              className="px-5 py-4"
              style={{ borderRight: '1px solid #F0EAE0' }}
            >

              {/* BASIC INFORMATION */}
              <div className="form-section mb-4 pb-4">
                <p className="section-label">Basic Information</p>

                {/* Form.Group — react-bootstrap */}
                <Form.Group className="mb-3">
                  <div className="d-flex justify-content-between align-items-center mb-1">
                    {/* Form.Label — react-bootstrap */}
                    <Form.Label className="form-label mb-0">KPI Title</Form.Label>
                    <span style={{ fontSize: '11px', color: 'var(--text-muted)' }}>
                      {form.title.length} / 60
                    </span>
                  </div>
                  {/* Form.Control — react-bootstrap */}
                  <Form.Control
                    type="text"
                    className="form-control-light"
                    placeholder="Monthly sales revenue target"
                    maxLength={60}
                    value={form.title}
                    onChange={(e) => set('title', e.target.value)}
                  />
                </Form.Group>

                {/* Form.Group — react-bootstrap */}
                <Form.Group className="mb-3">
                  {/* Form.Label — react-bootstrap */}
                  <Form.Label className="form-label">
                    Description — what does the KPI measure?
                  </Form.Label>
                  {/* Form.Control (textarea) — react-bootstrap */}
                  <Form.Control
                    as="textarea"
                    rows={3}
                    className="form-control-light"
                    placeholder="Total revenue generated by the assigned staff member within the calendar month…"
                    value={form.description}
                    onChange={(e) => set('description', e.target.value)}
                  />
                </Form.Group>

                {/* Row — react-bootstrap */}
                <Row className="g-2">
                  {/* Col — react-bootstrap */}
                  <Col>
                    {/* Form.Group — react-bootstrap */}
                    <Form.Group>
                      {/* Form.Label — react-bootstrap */}
                      <Form.Label className="form-label">Category</Form.Label>
                      {/* Form.Select — react-bootstrap */}
                      <Form.Select
                        className="form-control-light"
                        value={form.category}
                        onChange={(e) => set('category', e.target.value)}
                      >
                        <option value="">Select category</option>
                        <option value="Target">Target</option>
                        <option value="Project">Project</option>
                      </Form.Select>
                    </Form.Group>
                  </Col>
                  {/* Col — react-bootstrap */}
                  <Col>
                    <Form.Group>
                      <Form.Label className="form-label">Department</Form.Label>
                      {/* Form.Select — react-bootstrap */}
                      <Form.Select
                        className="form-control-light"
                        value={form.department}
                        onChange={(e) => set('department', e.target.value)}
                      >
                        <option value="">Select department</option>
                        <option value="Business Development">Business Development</option>
                        <option value="Marketing">Marketing</option>
                        <option value="Operations">Operations</option>
                        <option value="Finance">Finance</option>
                      </Form.Select>
                    </Form.Group>
                  </Col>
                </Row>
              </div>

              {/* TARGET & MEASUREMENT */}
              <div className="form-section mb-4 pb-4">
                <p className="section-label">Target &amp; Measurement</p>
                {/* Row — react-bootstrap */}
                <Row className="g-2">
                  {/* Col — react-bootstrap */}
                  <Col md={4}>
                    <Form.Group>
                      <Form.Label className="form-label">Target Value</Form.Label>
                      {/* Form.Control — react-bootstrap */}
                      <Form.Control
                        type="number"
                        className="form-control-light"
                        placeholder="0"
                        value={form.targetValue}
                        onChange={(e) => set('targetValue', e.target.value)}
                      />
                    </Form.Group>
                  </Col>
                  {/* Col — react-bootstrap */}
                  <Col md={4}>
                    <Form.Group>
                      <Form.Label className="form-label">Unit of Measurement</Form.Label>
                      {/* Form.Control — react-bootstrap */}
                      <Form.Control
                        type="text"
                        className="form-control-light"
                        placeholder="e.g. events, RM, %"
                        value={form.unit}
                        onChange={(e) => set('unit', e.target.value)}
                      />
                    </Form.Group>
                  </Col>
                  {/* Col — react-bootstrap */}
                  <Col md={4}>
                    <Form.Group>
                      <Form.Label className="form-label">Direction</Form.Label>
                      {/* Form.Select — react-bootstrap */}
                      <Form.Select
                        className="form-control-light"
                        value={form.direction}
                        onChange={(e) => set('direction', e.target.value)}
                      >
                        <option value="Amount">Amount (↑)</option>
                        <option value="Amount Down">Amount (↓)</option>
                        <option value="Percentage">Percentage (%)</option>
                      </Form.Select>
                    </Form.Group>
                  </Col>
                </Row>
              </div>

              {/* TIMELINE */}
              <div className="form-section mb-4 pb-4">
                <p className="section-label">Timeline</p>
                {/* Row — react-bootstrap */}
                <Row className="g-2 mb-3">
                  {/* Col — react-bootstrap */}
                  <Col>
                    <Form.Group>
                      <Form.Label className="form-label">Start Date</Form.Label>
                      {/* Form.Control (date) — react-bootstrap */}
                      <Form.Control
                        type="date"
                        className="form-control-light"
                        value={form.startDate}
                        onChange={(e) => set('startDate', e.target.value)}
                      />
                    </Form.Group>
                  </Col>
                  {/* Col — react-bootstrap */}
                  <Col>
                    <Form.Group>
                      <Form.Label className="form-label">Deadline</Form.Label>
                      {/* Form.Control (date) — react-bootstrap */}
                      <Form.Control
                        type="date"
                        className="form-control-light"
                        value={form.deadline}
                        onChange={(e) => set('deadline', e.target.value)}
                      />
                    </Form.Group>
                  </Col>
                </Row>

                <Form.Label className="form-label mb-2">
                  Milestone checkpoints{' '}
                  <span className="text-muted fw-normal">(optional)</span>
                </Form.Label>

                <div className="milestones-list">
                  {form.milestones.map((m) => (
                    /* MilestoneRow — reusable component from /component/MilestoneRow.jsx */
                    <MilestoneRow
                      key={m.id}
                      milestone={m}
                      onChange={(updated) => updateMilestone(m.id, updated)}
                      onRemove={() => removeMilestone(m.id)}
                    />
                  ))}
                </div>

                {/* Button (link) — react-bootstrap */}
                <Button
                  variant="link"
                  className="p-0 text-decoration-none"
                  style={{ color: 'var(--accent-orange)', fontSize: '13px' }}
                  onClick={addMilestone}
                >
                  + Add milestone
                </Button>
              </div>

              {/* EVIDENCE REQUIREMENT */}
              <div className="form-section">
                <p className="section-label">Evidence Requirement</p>

                <div className="evidence-options mb-3">
                  {/* Form.Check — react-bootstrap */}
                  <Form.Check
                    type="checkbox"
                    id="ev-pdf"
                    label="PDF Documents"
                    checked={form.evidencePdf}
                    onChange={(e) => set('evidencePdf', e.target.checked)}
                  />
                  {/* Form.Check — react-bootstrap */}
                  <Form.Check
                    type="checkbox"
                    id="ev-images"
                    label="Images (JPG, PNG)"
                    checked={form.evidenceImages}
                    onChange={(e) => set('evidenceImages', e.target.checked)}
                  />
                  {/* Form.Check — react-bootstrap */}
                  <Form.Check
                    type="checkbox"
                    id="ev-spreadsheet"
                    label="Spreadsheet Files (XLSX)"
                    checked={form.evidenceSpreadsheet}
                    onChange={(e) => set('evidenceSpreadsheet', e.target.checked)}
                  />
                </div>

                {/* Form.Group — react-bootstrap */}
                <Form.Group>
                  {/* Form.Label — react-bootstrap */}
                  <Form.Label className="form-label">Instructions for staff</Form.Label>
                  {/* Form.Control (textarea) — react-bootstrap */}
                  <Form.Control
                    as="textarea"
                    rows={3}
                    className="form-control-light"
                    placeholder="Add any specific instructions for staff when submitting evidence…"
                    value={form.staffInstructions}
                    onChange={(e) => set('staffInstructions', e.target.value)}
                  />
                </Form.Group>
              </div>
            </Col>

            {/* ── RIGHT: Assigned + Actions ───────────────────────── */}
            {/* Col — react-bootstrap */}
            <Col md={5} className="px-5 py-4">
              <p className="section-label">Currently Assigned</p>

              {isEdit ? (
                <>
                  {/* Staff list */}
                  <div className="mb-3">
                    {ASSIGNED_STAFF.map((s, idx) => (
                      <div
                        key={idx}
                        className="d-flex align-items-center gap-2 mb-2"
                      >
                        <div
                          style={{
                            width: '32px',
                            height: '32px',
                            borderRadius: '50%',
                            backgroundColor: s.bg,
                            color: s.color,
                            display: 'flex',
                            alignItems: 'center',
                            justifyContent: 'center',
                            fontWeight: 700,
                            fontSize: '11px',
                            flexShrink: 0,
                          }}
                        >
                          {s.initials}
                        </div>
                        <span style={{ fontSize: '13px', fontWeight: 500 }}>
                          {s.name}
                        </span>
                      </div>
                    ))}
                  </div>

                  {/* Button (link) — react-bootstrap */}
                  <Button
                    variant="link"
                    className="p-0 text-decoration-none d-flex align-items-center gap-1 mb-4"
                    style={{ color: 'var(--accent-orange)', fontSize: '12px' }}
                    onClick={() => navigate('/manager/assign')}
                  >
                    Manage at assignment center <ChevronRight size={12} />
                  </Button>

                  <hr style={{ borderColor: '#F0EAE0' }} />

                  {/* Archive / Delete */}
                  <div className="mt-4">
                    {/* Button (danger) — react-bootstrap */}
                    <Button
                      className="w-100 mb-2"
                      style={{
                        backgroundColor: 'var(--accent-orange)',
                        border: 'none',
                        fontWeight: 600,
                        fontSize: '13px',
                        borderRadius: '8px',
                        padding: '10px',
                      }}
                    >
                      Archive KPI
                    </Button>
                    <p style={{ fontSize: '11px', color: 'var(--text-muted)', marginBottom: '8px' }}>
                      Archiving is permanent and cannot be undone.
                    </p>
                    {/* Button (link/danger) — react-bootstrap */}
                    <Button
                      variant="link"
                      className="p-0 text-decoration-none"
                      style={{ color: '#DC3545', fontSize: '12px' }}
                    >
                      Delete permanently
                    </Button>
                  </div>
                </>
              ) : (
                /* Empty state when creating a new KPI */
                <div
                  style={{
                    padding: '20px',
                    borderRadius: '10px',
                    backgroundColor: '#F9F7F4',
                    border: '1px dashed #D8CFC2',
                    textAlign: 'center',
                    color: 'var(--text-muted)',
                  }}
                >
                  <PersonFill size={24} className="mb-2" style={{ opacity: 0.4 }} />
                  <p style={{ fontSize: '13px', marginBottom: '8px' }}>
                    No staff assigned yet
                  </p>
                  {/* Button (link) — react-bootstrap */}
                  <Button
                    variant="link"
                    className="p-0 text-decoration-none"
                    style={{ color: 'var(--accent-orange)', fontSize: '12px' }}
                    onClick={() => navigate('/manager/assign')}
                  >
                    Go to assignment center →
                  </Button>
                </div>
              )}
            </Col>
          </Row>
        </Card.Body>
        </Card>
      </div>
    </div>
  );
};

export default CreateEditKpi;
